<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictsSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->insert([
            array (
  'id' => 1,
  'district_name' => 'Meru District',
  'region_id' => '1',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 2,
  'district_name' => 'Arusha City',
  'region_id' => '1',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 3,
  'district_name' => 'Arusha District',
  'region_id' => '1',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 4,
  'district_name' => 'Karatu District',
  'region_id' => '1',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 5,
  'district_name' => 'Longido District',
  'region_id' => '1',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 6,
  'district_name' => 'Monduli District',
  'region_id' => '1',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 7,
  'district_name' => 'Ngorongoro District',
  'region_id' => '1',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 8,
  'district_name' => 'Ilala Municipal',
  'region_id' => '2',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 9,
  'district_name' => 'Kinondoni Municipal',
  'region_id' => '2',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 10,
  'district_name' => 'Temeke Municipal',
  'region_id' => '2',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 11,
  'district_name' => 'Kigamboni Municipal',
  'region_id' => '2',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 12,
  'district_name' => 'Ubungo Municipal',
  'region_id' => '2',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 13,
  'district_name' => 'Bahi District',
  'region_id' => '3',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 14,
  'district_name' => 'Chamwino District',
  'region_id' => '3',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 15,
  'district_name' => 'Chemba District',
  'region_id' => '3',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 16,
  'district_name' => 'Dodoma Municipal',
  'region_id' => '3',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 17,
  'district_name' => 'Kondoa District',
  'region_id' => '3',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 18,
  'district_name' => 'Kongwa District',
  'region_id' => '3',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 19,
  'district_name' => 'Mpwapwa District',
  'region_id' => '3',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 20,
  'district_name' => 'Bukombe District',
  'region_id' => '4',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 21,
  'district_name' => 'Chato District',
  'region_id' => '4',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 22,
  'district_name' => 'Geita Town',
  'region_id' => '4',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 23,
  'district_name' => 'Mbogwe District',
  'region_id' => '4',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 24,
  'district_name' => 'Nyang\'hwale District',
  'region_id' => '4',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 25,
  'district_name' => 'Iringa District',
  'region_id' => '5',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 26,
  'district_name' => 'Iringa Municipal',
  'region_id' => '5',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 27,
  'district_name' => 'Kilolo District',
  'region_id' => '5',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 28,
  'district_name' => 'Mafinga Town',
  'region_id' => '5',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 29,
  'district_name' => 'Mufindi District',
  'region_id' => '5',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 30,
  'district_name' => 'Biharamulo District',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 31,
  'district_name' => 'Bukoba District',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 32,
  'district_name' => 'Bukoba Municipal',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 33,
  'district_name' => 'Karagwe District',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 34,
  'district_name' => 'Kyerwa District',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 35,
  'district_name' => 'Missenyi District',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 36,
  'district_name' => 'Muleba District',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 37,
  'district_name' => 'Ngara District',
  'region_id' => '6',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 38,
  'district_name' => 'Mlele District',
  'region_id' => '7',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 39,
  'district_name' => 'Mpanda District',
  'region_id' => '7',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 40,
  'district_name' => 'Mpanda Town',
  'region_id' => '7',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 41,
  'district_name' => 'Buhigwe District',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 42,
  'district_name' => 'Kakonko District',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 43,
  'district_name' => 'Kasulu District',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 44,
  'district_name' => 'Kasulu Town',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 45,
  'district_name' => 'Kibondo District',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 46,
  'district_name' => 'Kigoma District',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 47,
  'district_name' => 'Kigoma-Ujiji Municipal',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 48,
  'district_name' => 'Uvinza District',
  'region_id' => '8',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 49,
  'district_name' => 'Hai District',
  'region_id' => '9',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 50,
  'district_name' => 'Moshi District',
  'region_id' => '9',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 51,
  'district_name' => 'Moshi Municipal',
  'region_id' => '9',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 52,
  'district_name' => 'Mwanga District',
  'region_id' => '9',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 53,
  'district_name' => 'Rombo District',
  'region_id' => '9',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 54,
  'district_name' => 'Same District',
  'region_id' => '9',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 55,
  'district_name' => 'Siha District',
  'region_id' => '9',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 56,
  'district_name' => 'Chake Chake District',
  'region_id' => '19',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 57,
  'district_name' => 'Mkoani District',
  'region_id' => '19',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 58,
  'district_name' => 'Kati District',
  'region_id' => '31',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 59,
  'district_name' => 'Kusini District',
  'region_id' => '31',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 60,
  'district_name' => 'Kilwa District',
  'region_id' => '10',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 61,
  'district_name' => 'Lindi District',
  'region_id' => '10',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 62,
  'district_name' => 'Lindi Municipal',
  'region_id' => '10',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 63,
  'district_name' => 'Liwale District',
  'region_id' => '10',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 64,
  'district_name' => 'Nachingwea District',
  'region_id' => '10',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 65,
  'district_name' => 'Ruangwa District',
  'region_id' => '10',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 66,
  'district_name' => 'Babati Town',
  'region_id' => '11',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 67,
  'district_name' => 'Babati District',
  'region_id' => '11',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 68,
  'district_name' => 'Hanang District',
  'region_id' => '11',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 69,
  'district_name' => 'Kiteto District',
  'region_id' => '11',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 70,
  'district_name' => 'Mbulu District',
  'region_id' => '11',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 71,
  'district_name' => 'Simanjiro District',
  'region_id' => '11',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 72,
  'district_name' => 'Bunda District',
  'region_id' => '12',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 73,
  'district_name' => 'Butiama District',
  'region_id' => '12',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 74,
  'district_name' => 'Musoma District',
  'region_id' => '12',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 75,
  'district_name' => 'Musoma Municipal',
  'region_id' => '12',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 76,
  'district_name' => 'Rorya District',
  'region_id' => '12',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 77,
  'district_name' => 'Serengeti District',
  'region_id' => '12',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 78,
  'district_name' => 'Tarime District',
  'region_id' => '12',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 79,
  'district_name' => 'Busokelo District',
  'region_id' => '13',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 80,
  'district_name' => 'Chunya District',
  'region_id' => '13',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 81,
  'district_name' => 'Kyela District',
  'region_id' => '13',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 82,
  'district_name' => 'Mbarali City',
  'region_id' => '13',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 83,
  'district_name' => 'Mbeya District',
  'region_id' => '13',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 84,
  'district_name' => 'Mbeya District',
  'region_id' => '13',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 85,
  'district_name' => 'Rungwe',
  'region_id' => '13',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 86,
  'district_name' => 'Magharibi District',
  'region_id' => '30',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 87,
  'district_name' => 'Mjini District',
  'region_id' => '30',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 88,
  'district_name' => 'Gairo District',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 89,
  'district_name' => 'Kilombero District',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 90,
  'district_name' => 'Kilosa District',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 91,
  'district_name' => 'Morogoro District',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 92,
  'district_name' => 'Morogoro Municipal',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 93,
  'district_name' => 'Mvomero District',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 94,
  'district_name' => 'Ulanga District',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 95,
  'district_name' => 'Malinyi District',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 96,
  'district_name' => 'Ifakara Township',
  'region_id' => '14',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 97,
  'district_name' => 'Masasi District',
  'region_id' => '15',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 98,
  'district_name' => 'Masasi Town',
  'region_id' => '15',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 99,
  'district_name' => 'Mtwara District',
  'region_id' => '15',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 100,
  'district_name' => 'Mtwara Municipal',
  'region_id' => '15',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 101,
  'district_name' => 'Nanyumbu District',
  'region_id' => '15',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 102,
  'district_name' => 'Newala District',
  'region_id' => '15',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 103,
  'district_name' => 'Tandahimba District',
  'region_id' => '15',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 104,
  'district_name' => 'Ilemela Municipal',
  'region_id' => '16',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 105,
  'district_name' => 'Kwimba District',
  'region_id' => '16',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 106,
  'district_name' => 'Magu District',
  'region_id' => '16',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 107,
  'district_name' => 'Misungwi District',
  'region_id' => '16',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 108,
  'district_name' => 'Nyamagana Municipal',
  'region_id' => '16',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 109,
  'district_name' => 'Sengerema District',
  'region_id' => '16',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 110,
  'district_name' => 'Ukerewe District',
  'region_id' => '16',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 111,
  'district_name' => 'Ludewa District',
  'region_id' => '17',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 112,
  'district_name' => 'Makambako Town',
  'region_id' => '17',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 113,
  'district_name' => 'Makete District',
  'region_id' => '17',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 114,
  'district_name' => 'Njombe District',
  'region_id' => '17',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 115,
  'district_name' => 'Njombe Town',
  'region_id' => '17',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 116,
  'district_name' => 'Wanging\'ombe District',
  'region_id' => '17',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 117,
  'district_name' => 'Bagamoyo District',
  'region_id' => '20',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 118,
  'district_name' => 'Kibaha District',
  'region_id' => '20',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 119,
  'district_name' => 'Kibaha Town',
  'region_id' => '20',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 120,
  'district_name' => 'Kisarawe District',
  'region_id' => '20',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 121,
  'district_name' => 'Mafia District',
  'region_id' => '20',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 122,
  'district_name' => 'Mkuranga District',
  'region_id' => '20',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 123,
  'district_name' => 'Rufiji District',
  'region_id' => '20',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 124,
  'district_name' => 'Kalambo District',
  'region_id' => '21',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 125,
  'district_name' => 'Nkasi District',
  'region_id' => '21',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 126,
  'district_name' => 'Sumbawanga District',
  'region_id' => '21',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 127,
  'district_name' => 'Sumbawanga Municipal',
  'region_id' => '21',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 128,
  'district_name' => 'Mbinga District',
  'region_id' => '22',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 129,
  'district_name' => 'Songea District',
  'region_id' => '22',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 130,
  'district_name' => 'Songea Municipal',
  'region_id' => '22',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 131,
  'district_name' => 'Tunduru District',
  'region_id' => '22',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 132,
  'district_name' => 'Namtumbo District',
  'region_id' => '22',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 133,
  'district_name' => 'Nyasa District',
  'region_id' => '22',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 134,
  'district_name' => 'Kahama Town',
  'region_id' => '23',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 135,
  'district_name' => 'Kahama District',
  'region_id' => '23',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 136,
  'district_name' => 'Kishapu District',
  'region_id' => '23',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 137,
  'district_name' => 'Shinyanga District',
  'region_id' => '23',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 138,
  'district_name' => 'Shinyanga Municipal',
  'region_id' => '23',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 139,
  'district_name' => 'Bariadi District',
  'region_id' => '24',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 140,
  'district_name' => 'Busega District',
  'region_id' => '24',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 141,
  'district_name' => 'Itilima District',
  'region_id' => '24',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 142,
  'district_name' => 'Maswa District',
  'region_id' => '24',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 143,
  'district_name' => 'Meatu District',
  'region_id' => '24',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 144,
  'district_name' => 'Ikungi District',
  'region_id' => '25',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 145,
  'district_name' => 'Iramba District',
  'region_id' => '25',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 146,
  'district_name' => 'Manyoni District',
  'region_id' => '25',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 147,
  'district_name' => 'Mkalama District',
  'region_id' => '25',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 148,
  'district_name' => 'Singida District',
  'region_id' => '25',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 149,
  'district_name' => 'Singida Municipal',
  'region_id' => '25',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 150,
  'district_name' => 'Ileje District',
  'region_id' => '26',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 151,
  'district_name' => 'Mbozi District',
  'region_id' => '26',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 152,
  'district_name' => 'Momba District',
  'region_id' => '26',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 153,
  'district_name' => 'Songwe District',
  'region_id' => '26',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 154,
  'district_name' => 'Igunga District',
  'region_id' => '27',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 155,
  'district_name' => 'Kaliua District',
  'region_id' => '27',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 156,
  'district_name' => 'Nzega District',
  'region_id' => '27',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 157,
  'district_name' => 'Sikonge District',
  'region_id' => '27',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 158,
  'district_name' => 'Tabora Municipal',
  'region_id' => '27',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 159,
  'district_name' => 'Urambo District',
  'region_id' => '27',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 160,
  'district_name' => 'Uyui District',
  'region_id' => '27',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 161,
  'district_name' => 'Handeni District',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 162,
  'district_name' => 'Handeni Town',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 163,
  'district_name' => 'Kilindi District',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 164,
  'district_name' => 'Korogwe Town',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 165,
  'district_name' => 'Korogwe District',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 166,
  'district_name' => 'Lushoto District',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 167,
  'district_name' => 'Muheza District',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 168,
  'district_name' => 'Mkinga District',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 169,
  'district_name' => 'Pangani District',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 170,
  'district_name' => 'Tanga City',
  'region_id' => '28',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 171,
  'district_name' => 'Kaskazini A District',
  'region_id' => '29',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 172,
  'district_name' => 'Kaskazini B District',
  'region_id' => '29',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 173,
  'district_name' => 'Micheweni District',
  'region_id' => '19',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 174,
  'district_name' => 'Wete District',
  'region_id' => '19',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 175,
  'district_name' => 'Unguja Magharibi District',
  'region_id' => '30',
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 176,
  'district_name' => 'Unguja Mjini District',
  'region_id' => '30',
  'created_at' => NULL,
  'updated_at' => NULL,
)
        ]);
    }
}